# Generated by Django 4.2.27 on 2026-01-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='custom_description',
            field=models.CharField(blank=True, help_text='Description for custom items (old dues, legacy items, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True for custom/manual entries'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch this item was sold from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product'),
        ),
    ]
