# Generated by Django 6.0.6 on 2026-07-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_custom_description_saleitem_is_custom_and_more'),
        ('warehouse', '0002_remove_stocktransferitem_destination_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='batch',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse fulfilled from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='warehouse.warehouse'),
        ),
    ]
