# Generated by Django 6.0.6 on 2026-07-28 12:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_saleitem_batch_saleitem_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Cost price for profit calculation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
