# Generated by Django 4.2.30 on 2026-07-31 19:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_repair_sale_status_and_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(db_index=True),
        ),
    ]
