# Generated by Django 6.0.6 on 2026-08-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_shipping_amount_alter_sale_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='shipping_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
    ]
