# Generated by Django 6.0.6 on 2026-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_sale_shipping_amount_remove_sale_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity returned so far'),
        ),
    ]
