# Generated by Django 4.2.30 on 2026-06-08 03:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_unique_phone_email_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customer credit/wallet balance (advance amount)', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('cheque', 'Cheque'), ('credit_balance', 'Credit Balance')], default='cash', max_length=20),
        ),
    ]
