# Generated by Django 6.0.6 on 2026-07-28 09:40

from django.db import migrations


def create_default_walkin_customer(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    
    # We use get_or_create to ensure it runs safely multiple times or on fresh deploys
    Customer.objects.get_or_create(
        phone='0000000000',
        defaults={
            'name': 'Walk-In Customer',
            'email': 'walkin@example.com',
            'address': 'N/A'
        }
    )

def remove_default_walkin_customer(apps, schema_editor):
    # Optional reverse migration logic (safest to just pass, to not accidentally delete history)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_unique_phone_email_constraints'),
    ]

    operations = [
        migrations.RunPython(create_default_walkin_customer, remove_default_walkin_customer),
    ]
