# Generated by Django 4.2.30 on 2026-06-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_credit_balance_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_email',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_customer_email', violation_error_message='A customer with this email address already exists.'),
        ),
    ]
