# Generated by Django 6.0.6 on 2026-08-04 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_name_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number (e.g. 01712345678 or +8801712345678).', regex='^(?:\\+?88)?01[3-9]\\d{8}$')]),
        ),
    ]
