# Generated by Django 6.0.6 on 2026-08-04 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_phone',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A customer with this phone number already exists.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number (e.g. 01712345678 or +8801712345678).', regex='^(?:\\+?88)?01[3-9]\\d{8}$')]),
        ),
    ]
