# Generated by Django 4.2.30 on 2026-08-16 08:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_customer_unique_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('set_opening_balance', 'Can set customer opening balance')]},
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding debt from before this system was introduced', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Effective date of the opening balance'),
        ),
    ]
