# Generated by Django 5.2.10 on 2026-01-12 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, help_text='Shop name displayed across the system', max_length=200)),
                ('license_expiry_date', models.DateField(blank=True, help_text='Server/license expiry date', null=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Products with stock at or below this level are considered low stock')),
                ('alert_days_before_expiry', models.PositiveIntegerField(default=30, help_text='Number of days before expiry to start showing alerts')),
                ('currency_symbol', models.CharField(default='৳', help_text='Currency symbol for prices', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
