# Generated by Django 4.2.30 on 2026-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shop logo displayed on invoices and pages', null=True, upload_to='settings/'),
        ),
    ]
