# Generated by Django 6.0.6 on 2026-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='shop_address',
            field=models.TextField(blank=True, help_text='Shop address used on invoices and reports'),
        ),
    ]
