# Generated by Django 6.1.1 on 2026-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_system_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRANSFER', 'Transfer'), ('SALE', 'Sale'), ('PAYMENT', 'Payment'), ('SALE_RETURN', 'Sale Return'), ('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out')], max_length=20),
        ),
    ]
