# Generated by Django 4.2.30 on 2026-06-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='shop_address',
            field=models.TextField(blank=True, help_text='Shop physical address displayed on invoices'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='shop_email',
            field=models.CharField(blank=True, help_text='Shop email address displayed on invoices', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='shop_phone',
            field=models.CharField(blank=True, help_text='Shop phone number displayed on invoices', max_length=50),
        ),
    ]
