# Generated by Django 6.0.6 on 2026-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_walkin_customers',
            field=models.BooleanField(default=True, help_text='Allow sales to walk-in customers without an account'),
        ),
    ]
