# Generated by Django 4.2.30 on 2026-06-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings_shop_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('TRANSFER', 'Transfer'), ('SALE', 'Sale'), ('PAYMENT', 'Payment'), ('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('RETURN', 'Return')], max_length=20),
        ),
    ]
