# Generated by Django 4.2.30 on 2026-08-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_allow_walkin_customers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_sales_report', 'Can view sales report'), ('view_profit_report', 'Can view profit report'), ('view_stock_report', 'Can view stock report'), ('view_transfer_report', 'Can view transfer history report'), ('view_dead_stock_report', 'Can view dead stock report'), ('view_audit_logs', 'Can view audit logs')], 'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
    ]
