# Generated by Django 4.2.30 on 2026-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_allow_walkin_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='shop_logo',
            field=models.ImageField(blank=True, help_text='Shop logo used on invoices and reports', null=True, upload_to='shop_logo/'),
        ),
    ]
