# Generated by Django 4.2.30 on 2026-08-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_systemsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='avg_cost_visibility',
            field=models.CharField(choices=[('admin_only', 'Admin Only'), ('all_users', 'All Users')], default='admin_only', help_text='Who can view the average cost of products', max_length=20),
        ),
    ]
