# Generated by Django 4.2.30 on 2026-08-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemsettings_avg_cost_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo used across invoices and print pages', null=True, upload_to='logos/'),
        ),
    ]
