# Generated by Django 6.0.6 on 2026-07-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_batch_product_remove_batch_warehouse_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='destination_batch',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='source_batch',
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.product'),
        ),
    ]
