# Generated by Django 4.2.30 on 2026-08-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehouse_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='is_shop',
            field=models.BooleanField(default=False, help_text='Is this a shop location?'),
        ),
    ]
