# Generated by Django 4.2.27 on 2026-01-11 17:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stockout_number', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('damage', 'Damaged'), ('loss', 'Lost/Theft'), ('expired', 'Expired'), ('internal', 'Internal Use'), ('adjustment', 'Stock Adjustment'), ('return_supplier', 'Return to Supplier'), ('sample', 'Sample/Display'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stockout_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the stock out')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total value of stock removed (at cost price)', max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outs', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Out',
                'verbose_name_plural': 'Stock Outs',
                'ordering': ['-stockout_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price per unit at time of stock out', max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stockout_items', to='inventory.batch')),
                ('stockout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockout')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
