# Generated by Django 4.2.27 on 2026-01-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockout_stockoutitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
