# Generated by Django 6.0.6 on 2026-07-28 12:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_name_field'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stockoutitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='batch',
        ),
        migrations.AddField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='stockoutitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stockout_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockoutitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost price per unit at time of stock out (Avg Cost)', max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Product Stocks',
            },
        ),
    ]
