# Generated by Django 6.0.6 on 2026-07-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_batch_product_remove_batch_warehouse_and_more'),
        ('sales', '0003_remove_saleitem_batch_saleitem_warehouse'),
        ('warehouse', '0002_remove_stocktransferitem_destination_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together={('product', 'warehouse')},
        ),
    ]
