# Generated by Django 6.0.6 on 2026-07-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_delete_batch_alter_productstock_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
