# Generated by Django 6.0.6 on 2026-08-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_image'),
        ('warehouse', '0002_remove_stocktransferitem_destination_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_stocks', to='warehouse.warehouse'),
        ),
    ]
