# Generated by Django 6.0.6 on 2026-08-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_productstock_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
