# Generated by Django 4.2.30 on 2026-09-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text='e.g. sale_created, payment_received', max_length=50)),
                ('event_id', models.CharField(db_index=True, help_text='Unique identifier for the event (e.g. sale PK)', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='Telegram Bot API token (from @BotFather)', max_length=255)),
                ('chat_id', models.CharField(blank=True, help_text='Telegram chat/group ID to send notifications to', max_length=100)),
                ('apprise_url', models.CharField(blank=True, editable=False, help_text='Auto-built Apprise URL from bot_token and chat_id', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Setting',
                'verbose_name_plural': 'Telegram Settings',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('event_type', 'event_id'), name='unique_notification_event'),
        ),
    ]
